/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projectgerir.view.popUp;

import br.com.projectgerir.model.DAO.CategoriaDAO;
import br.com.projectgerir.model.bean.Categoria;
import static br.com.projectgerir.view.TelaAddDespesa.readCategoria;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kaiqu
 */
public class TelaAddCategoria extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUsuarioSDI
     */
    public TelaAddCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddCategoria = new javax.swing.JButton();
        txtNomeCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERIR - ADICIONAR CATEGORIA");
        setBackground(new java.awt.Color(19, 7, 46));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 7, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCategoria.setContentAreaFilled(false);
        btnAddCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCategoria.setFocusable(false);
        btnAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, 40));

        txtNomeCategoria.setBackground(new java.awt.Color(19, 7, 46));
        txtNomeCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCategoria.setBorder(null);
        txtNomeCategoria.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNomeCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeCategoriaKeyPressed(evt);
            }
        });
        jPanel1.add(txtNomeCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 113, 230, 24));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projectgerir/images/imgTelaAddCategoria.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 470, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 269));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void adicionarCategoria(){
        Categoria c = new Categoria();
        CategoriaDAO cDao = new CategoriaDAO();
        
        c.setNomeCategoria(txtNomeCategoria.getText());
        
        try{
            cDao.create(c);
            txtNomeCategoria.setText("");
            readCategoria();
   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro so salvar categoria: "+ex);
        }
    }
    
    private void btnAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoriaActionPerformed
        adicionarCategoria();
    }//GEN-LAST:event_btnAddCategoriaActionPerformed

    private void txtNomeCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCategoriaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            adicionarCategoria();
        }
    }//GEN-LAST:event_txtNomeCategoriaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeCategoria;
    // End of variables declaration//GEN-END:variables
}
