package br.com.projectgerir.view.popUp;


/**
 *
 * @author kaiqu
 */
public class TelaEditarDespesa extends javax.swing.JDialog {

    /**
     * Creates new form TelaEditarDespesa
     */
    public TelaEditarDespesa(java.awt.Frame parent, boolean modal, int idDespesa, String valor, String descricao, String data) {
        super(parent, modal);
        initComponents();
        
        txtDescricaoTelaEdicao.setText(descricao);
        txtValorTelaEditar.setText(valor);
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbFornecedorTelaEdicao = new javax.swing.JComboBox<>();
        txtValorTelaEditar = new javax.swing.JTextField();
        cbCategoriaTelaEdicao = new javax.swing.JComboBox<>();
        cbBancoTelaEdicao = new javax.swing.JComboBox<>();
        txtDataTelaEdicao = new javax.swing.JFormattedTextField();
        txtDescricaoTelaEdicao = new javax.swing.JTextField();
        imgTelaEditarDespesa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Despesa");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbFornecedorTelaEdicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbFornecedorTelaEdicao.setBorder(null);
        jPanel1.add(cbFornecedorTelaEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 147, 332, 27));

        txtValorTelaEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtValorTelaEditar.setBorder(null);
        jPanel1.add(txtValorTelaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 110, 27));

        cbCategoriaTelaEdicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbCategoriaTelaEdicao.setBorder(null);
        jPanel1.add(cbCategoriaTelaEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 79, 144, 27));

        cbBancoTelaEdicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbBancoTelaEdicao.setBorder(null);
        jPanel1.add(cbBancoTelaEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 79, 144, 27));

        txtDataTelaEdicao.setBorder(null);
        try {
            txtDataTelaEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataTelaEdicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtDataTelaEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 80, 113, 27));

        txtDescricaoTelaEdicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDescricaoTelaEdicao.setBorder(null);
        jPanel1.add(txtDescricaoTelaEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 147, 270, 27));

        imgTelaEditarDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projectgerir/images/TelaEditarDespesaV4.png"))); // NOI18N
        jPanel1.add(imgTelaEditarDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEditarDespesa dialog = new TelaEditarDespesa(new javax.swing.JFrame(), true, 0, "", "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<Object> cbBancoTelaEdicao;
    public static javax.swing.JComboBox<Object> cbCategoriaTelaEdicao;
    public static javax.swing.JComboBox<Object> cbFornecedorTelaEdicao;
    private javax.swing.JLabel imgTelaEditarDespesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtDataTelaEdicao;
    private javax.swing.JTextField txtDescricaoTelaEdicao;
    private javax.swing.JTextField txtValorTelaEditar;
    // End of variables declaration//GEN-END:variables
}
